services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Trueprogramming\Instagram\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Trueprogramming\Instagram\Domain\Repository\TokenRepository:
    public: true

  Trueprogramming\Instagram\DataProcessing\PostsDataProcessor:
    public: true
